apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-helm.fullname" . }}
  labels:
    app: {{ include "app-helm.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app-helm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app-helm.name" . }}
    spec:
      containers:
      - name: web
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: {{ include "app-helm.fullname" . }}-html
