apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-helm.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "app-helm.name" . }}
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: {{ .Values.nodePort }}
