apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-plain-staging
  namespace: argocd
spec:
  project: demo
  source:
    repoURL: REPO_URL
    targetRevision: main
    path: envs/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
