apiVersion: v1
kind: Service
metadata:
  name: app-plain
  namespace: prod
spec:
  type: NodePort
  selector:
    app: app-plain
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30083
